<h1>Preprocessing by a13ksa</h1>

Podaci su zanimljivi i korisni, dobro su sređeni i održavani, međutim potrebno je: <br>Izbaciti nepotrebne kolone  &#10004;&#65039;,  <br>Rešiti se noisy data  &#128307;, <br>Normalizovati tekstualne podatke &#10004;&#65039;,  <br> Izvršiti diskretizaciju podataka &#128307;

<h2>1. Čitanje podataka iz csv fajla</h2>

Otvaranje podataka u pythonu korišćenjem Pandas library <br>

In [143]:
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

data_set= pd.read_csv("jobs_in_data.csv")

sve = data_set.iloc[:,:].values # .ilos[:,:] znači svaka vrsta i svaka kolona
print(sve)

[[2023 'Data DevOps Engineer' 'Data Engineering' ... 'Hybrid' 'Germany'
  'L']
 [2023 'Data Architect' 'Data Architecture and Modeling' ... 'In-person'
  'United States' 'M']
 [2023 'Data Architect' 'Data Architecture and Modeling' ... 'In-person'
  'United States' 'M']
 ...
 [2021 'Principal Data Scientist' 'Data Science and Research' ...
  'Remote' 'United States' 'L']
 [2020 'Data Scientist' 'Data Science and Research' ... 'Remote'
  'United States' 'S']
 [2020 'Business Data Analyst' 'Data Analysis' ... 'Remote'
  'United States' 'L']]


Zbog ogromne količine kolona i vrsta tabela je skraćena sa ...

In [144]:
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

data_set= pd.read_csv("jobs_in_data.csv")

x = data_set.iloc[0,:].values # 1. vrsta
print(x)

print("---------------------")

x = data_set.iloc[:,4].values # 5. kolona
print(x)

[2023 'Data DevOps Engineer' 'Data Engineering' 'EUR' 88000 95012
 'Germany' 'Mid-level' 'Full-time' 'Hybrid' 'Germany' 'L']
---------------------
[ 88000 186000  81800 ... 151000 105000 100000]


<h2>2. Selekcija atributa</h2>

In [145]:
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd
data_set= pd.read_csv("jobs_in_data.csv")

x = pd.DataFrame(data_set.iloc[0:8,[1,5,7]].values) # Izbačene nepotrebne kolone

print(x)

                             0       1          2
0         Data DevOps Engineer   95012  Mid-level
1               Data Architect  186000     Senior
2               Data Architect   81800     Senior
3               Data Scientist  212000     Senior
4               Data Scientist   93300     Senior
5               Data Scientist  130000     Senior
6               Data Scientist  100000     Senior
7  Machine Learning Researcher  224400  Mid-level


<h2>3. Normalizacija tekstualnih podataka</h2>

In [146]:
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder    
data_set= pd.read_csv("jobs_in_data.csv")

x = data_set.iloc[:,[1,5,7]].values

label_encoder_x= LabelEncoder()  

x[:, 0]= label_encoder_x.fit_transform(x[:, 0])  # Kodiramo drugu kolonu

x[:, 2]= label_encoder_x.fit_transform(x[:, 2])  # Kodiramo treću kolonu

print(x)

[[42 95012 2]
 [41 186000 3]
 [41 81800 3]
 ...
 [114 151000 2]
 [69 105000 0]
 [21 100000 0]]


In [147]:
import numpy as np
import matplotlib.pyplot as mtp
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
data_set= pd.read_csv("jobs_in_data.csv")

x = data_set.iloc[:,[1,5,7]].values

ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0,1,2])],
    remainder='passthrough'
)

x = np.array(ct.fit_transform(x))

print(x)

  (0, 42)	1.0
  (0, 613)	1.0
  (0, 1913)	1.0
  (1, 41)	1.0
  (1, 1398)	1.0
  (1, 1914)	1.0
  (2, 41)	1.0
  (2, 504)	1.0
  (2, 1914)	1.0
  (3, 69)	1.0
  (3, 1561)	1.0
  (3, 1914)	1.0
  (4, 69)	1.0
  (4, 593)	1.0
  (4, 1914)	1.0
  (5, 69)	1.0
  (5, 937)	1.0
  (5, 1914)	1.0
  (6, 69)	1.0
  (6, 651)	1.0
  (6, 1914)	1.0
  (7, 102)	1.0
  (7, 1628)	1.0
  (7, 1913)	1.0
  (8, 102)	1.0
  :	:
  (9346, 1914)	1.0
  (9347, 69)	1.0
  (9347, 837)	1.0
  (9347, 1913)	1.0
  (9348, 11)	1.0
  (9348, 1907)	1.0
  (9348, 1913)	1.0
  (9349, 44)	1.0
  (9349, 164)	1.0
  (9349, 1913)	1.0
  (9350, 71)	1.0
  (9350, 1239)	1.0
  (9350, 1914)	1.0
  (9351, 69)	1.0
  (9351, 1905)	1.0
  (9351, 1914)	1.0
  (9352, 114)	1.0
  (9352, 1132)	1.0
  (9352, 1913)	1.0
  (9353, 69)	1.0
  (9353, 692)	1.0
  (9353, 1911)	1.0
  (9354, 21)	1.0
  (9354, 651)	1.0
  (9354, 1911)	1.0


Podaci su ovakvog tipa 1.00000000e+00, 0.00000000e+00, 0.00000000e+00 te se ne vide u ovoj konzoli
<!--
label_encoder_x= LabelEncoder()  

x[:, 0]= label_encoder_x.fit_transform(x[:, 0])  

x[:, 2]= label_encoder_x.fit_transform(x[:, 2])  
->